### ISSUE TITLE
set names not working in 0.4 versions

### ISSUE THREAD

**Issue by maciejorlos** [rstats-db/DBI#101]
Hi,
after change to 0.4 Version my code has crashed.
I send set names command to server 
`
mydb <- RMySQL::dbConnect(drv = RMySQL::MySQL(), user = as.character(creds$user), 
    password = as.character(creds$password), dbname = db_name, 
    host = host_name)
DBI::dbGetQuery(mydb, "SET NAMES UTF8")
`
it gives me :+1: 
`'value[[3L]](cond)': corrupt resultSet, missing fieldDescription`

I found this issue on stack: http://stackoverflow.com/questions/30932708/how-to-change-dplyrtbl-connection-encoding-to-utf8 but I am not sure if it's safe to set etc/mysql/my.cnf file or if there is any counterpart for Windows

**Comment by krlmlr** [comment]
This should be resolved by now, can you confirm?
