### ISSUE TITLE
Examples or vignette for binding

### ISSUE THREAD

**Issue by gaborcsardi** [rstats-db/DBI#105]
It is kinda hard to find out how it works. I'll write it at some point, if nobody gets to it before me.....

**Comment by krlmlr** [comment]
Closed by #67. Let me know what you think: http://rstats-db.github.io/DBI/dbBind.html (I've also reworked most existing examples, and added new ones).

**Comment by gaborcsardi** [comment]
Looks good, thanks! Typo: "Parametrised"
