### ISSUE TITLE
dbBind with a data frame

### ISSUE THREAD

**Issue by gaborcsardi** [rstats-db/DBI#106]
Is it possible? E.g. 
```
UPDATE tab SET col1 = $value WHERE col2 = $key;
```
and then bind it to a two-column data frame.
It would be great to have sg like this.

**Comment by krlmlr** [comment]
I think this shouldn't be the responsibility of dbBind(), but I can imagine a wrapper that repeatedly calls dbBind(). I know RMySQL currently has this, but it probably should go in the long run.

**Comment by gaborcsardi** [comment]
OK. I also realize that this is hard if the engine does not support it, and I don't know any that do. MySQL supports bulk inserts, but not updated AFAIR.

**Comment by krlmlr** [comment]
Multi-row bind will be supported: https://github.com/rstats-db/DBItest/issues/96.
