### ISSUE TITLE
Make sure database drivers tag strings with the correct encoding

### ISSUE THREAD

**Issue by bborgesr** [rstats-db/DBI#116]
At least for RMySQL, it seems that, currently, the driver uses the platform's default encoding, rather than provide and enforce the correct encoding.

For example, @jcheng5 created a MariaDB database (on AWS) whose encoding is set to UTF-8. However, when we try to read (and render in a Shiny app) the first 20 lines of one of the tables, we get an error (on Mac/Linux): `Error in gsub: input string 20 is invalid in this locale` (`gsub` is called from within a sanitize function from `xtable`). (That's the first place a non-ASCII character pops up.) If you examine the encoding of that string or any other in the table, you get:

``` r
Encoding(tbl[20,2])
#> [1] "unknown"
```

rather than "UTF-8" (as it was set) or "latin1" (the actual encoding in this case). So basically, RMySQL is not tagging the table with the correct encoding and, worse, it doesn't give us any clue what the encoding is -- so it is left up to the platform to use its default encoding. Now because this is different between Unix and Windows, there isn't _one_ fix we can apply. For example, the Shiny app mentioned above works fine on Windows and throws on Unix. If we had a fix like `Encoding(tbl[20,2]) <- "latin1"` or `dbExecute(conn, "SET NAMES utf8;")`, then it would work on Unix, but not on Windows...

So really, there isn't a good hack we can do for this. At this point, the best we can do is remove all non-ASCII characters from the database, which is really a bad non-solution to this issue...

Maybe could you make sure that drivers tag strings with the correct encoding in order to be considered DBI-compliant? As mentioned, we've encountered this for RMySQL, but @jcheng5 suspects this may be a problem for other drivers too...

cc @hadley

**Comment by krlmlr** [comment]
Thanks for the analysis, this should really be tested as part of DBItest (https://github.com/rstats-db/DBItest/issues/72). Drivers can simplify their lives by using the [utf8 class](https://github.com/krlmlr/utf8) (work in progress).

**Comment by krlmlr** [comment]
Fixed in https://github.com/rstats-db/DBItest/issues/72.
