### ISSUE TITLE
Bug in dbConnect (I think)

### ISSUE THREAD

**Issue by bborgesr** [rstats-db/DBI#118]
I came across this issue today, as I was trying to make sure all the different ways of specifying `drv` in a call to `dbConnect` were also supported in the `pool` package (in the `dbPool` function). 

So, in the `dbConnect` documentation, you have (itemized for ease of referencing here):

> `drv` 
> 1. an object that inherits from DBIDriver, or
> 2. a character string specifying the name of DBMS driver, e.g., "RSQLite", "RMySQL", "RPostgreSQL", or 
> 3. an existing DBIConnection object (in order to clone an existing connection).

Numbers 1 and 3 work. Number 2 didn't:

```r
conn <- DBI::dbConnect(drv = "RSQLite", "CollegeScorecard.sqlite")
 #> Error: Couldn't find driver RSQLite. Looked in:
 #> * global namespace
 #> * in package called RSQLite
 #> * in package called RRSQLite

conn3 <- DBI::dbConnect(drv = "SQLite", "CollegeScorecard.sqlite")
 #> Error in as.integer(from) : 
 #>  cannot coerce type 'S4' to vector of type 'integer'
```

It's easy to fix this in the `pool` package, but maybe I shouldn't do that if you either fix it in `DBI` or maybe just change the documentation to not allow option 2.

PS: Also if you do want to fix and keep option 2, the user should specify the driver (e.g. "SQLite"), rather than the package (e.g. "RSQLite"), right? You'd need to update the documentation...

**Comment by krlmlr** [comment]
I think that option 2 is deprecated, and the documentation is wrong here.
