### ISSUE TITLE
"Closing result set with pending rows" warning and partial result

### ISSUE THREAD

**Issue by DSLituiev** [rstats-db/DBI#119]
I am running the same `dbSendQuery( "SELECT...")` query on two systems (CentOS server and MacOSX local machine) on copies of the same file. On CentOS I am getting what I expect, and on Mac I get a shorter table of 500 rows and a warning:

`Warning message:
In sqliteSendQuery(conn, statement) : Closing result set with pending rows`

Is there way to find out what is going on?

**Comment by krlmlr** [comment]
Could you please file the issue against the RSQLite repository?

How many rows are there? Can you replicate the problem with a new database and some random data?
