### ISSUE TITLE
Think about subclasses of DBIResult

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#120]
https://github.com/rstats-db/DBI/issues/20#issuecomment-230805023

Or perhaps DBIResult is a superclass of DBIResultQuery and DBIResultStatement

**Comment by krlmlr** [comment]
Declaring subclasses of DBIResult in DBI is pointless, because the generics still need to be declared with `valueClass = "DBIResult"` for compatibility with older backends. The backends are free to make this distinction, though.

**Comment by imanuelcostigan** [comment]
@krlmlr indeed, RSQLServer has to.
