### ISSUE TITLE
Feature request: add a dbIsAlive() generic

### ISSUE THREAD

**Issue by bborgesr** [rstats-db/DBI#122]
The point of this function would be to use an existing connection and run a very simple query (which nonetheless requires a fully functioning connection) to ensure that the connection hasn't been timed out or broken somehow. For most DBMS, the query "SELECT 1" will work. Not all however (see [this stackoverflow answer](http://stackoverflow.com/a/3670000/6174455) for a good breakdown of existing validation queries).

**Comment by krlmlr** [comment]
I wonder if the existing `dbIsValid()` can be used here instead. A way to test it would be to serialize and deserialize the connection.

**Comment by bborgesr** [comment]
I think it'd be fine to use `dbIsValid()` for this, as long as it really checks the external connection. I think the only way to do so is to perform an existence query (e.g. `SELECT 1`) of some kind, right? I might be wrong, but my understanding was that the current `dbIsValid` only makes sure that the R wrapper around the connection has been open properly and has not yet been disconnected by the user (leaving open the possibility that the underlying connection is actually no longer valid for some reason).

**Comment by statwonk** [comment]
@bborgesr that comports with my understanding and experience with `dbIsValid`.

**Comment by krlmlr** [comment]
@statwonk: Thanks for your input. Could you name the DBI backends which behave like this according to your experience?

**Comment by krlmlr** [comment]
Closing for now.

**Comment by tusharp** [comment]
@krlmlr as mentioned in this thread  [here](http://stackoverflow.com/questions/41848862/how-to-check-if-the-connection-to-mysql-through-rmysql-persists-or-not) `dbIsValid`  throws an error if the connection is not closed for a long time. Tried this with MySQL 5.6. For now I am using `dbListConnections` to figure out if it returns an empty list or non-empty list to check.  Obviously as mentioned in the suggestions on the S.O. thread, if I close connections as soon as the results are fetched then no error occurs.
