### ISSUE TITLE
[dbGetQuery] Errors do not halt execution in parent functions

### ISSUE THREAD

**Issue by brendan-r** [rstats-db/DBI#125]
Hello,

Firstly, thanks for maintaining DBI!

This may be a bug, or it may be me misunderstanding how errors work with S4 classes.

*Assuming that `con` is a valid database connection*, I would expect invalid sql fed to the function below to hit an error when `dbGetquery` is called, and halt execution before printing the statement with `cat`. However, it doesn't; it hits the error in `dbGetquery`, and then continues executing.

```r
# Minimal reproducible example
f <- function(x) { 
  DBI::dbGetQuery(con, x)
  cat("--------------------  Still executin'...")
}
```

```
> f("lol")

Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "lol"
LINE 1: lol
        ^
)
--------------------  Still executin'...
Warning message:
In postgresqlQuickSQL(conn, statement, ...) : Could not create executelol
```

Trying to enforce halt-on-error behavior is tricky. Again, assuming that `con` is a valid database connection, ` try(DBI::dbGetQuery(con, "lol"))` errors, and then returns `NULL` -- not an object of class `try-error`.

**How can I write functions which wrap `dbGetQuery`, which halt execution if it errors?**

**Comment by krlmlr** [comment]
Raising an R error for an SQL error is definitely desired, but unfortunately cannot be enforced by DBI itself. There are tests in the companion test package, DBItest, but again not all DBI drivers are currently compliant to all DBI tests defined there.

Is it RPostgres or RPostgreSQL? For the latter, please look for a workaround; the former will eventually work, but don't hold your breath -- it may take a few months.

**Comment by brendan-r** [comment]
The latter. I had not realized that the error message was not an R error message. I can work around a NULL result. Thanks!

**Comment by bcipolli** [comment]
I would suggest re-opening this. This is pretty non-standard behavior and at the very least should be well-documented. 

Would also be great to keep an issue open to add heuristics to the code for dealing with this. I'd suggest that if we're not confident in the heuristics, we could have a flag to turn on/off heuristic-based failing.

Thx!

**Comment by krlmlr** [comment]
Backends that comply to the new DBI spec won't have this behavior. For other backends, you're on your own. This isn't a DBI problem, rather a problem of the backend in question.

I'll be working on RPostgres in November.
