### ISSUE TITLE
Move DBItest specification to DBI

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#129]
I feel that the prose for the DBI specification is best suited in this package, because it is actually useful for DBI users. The prose is tightly connected to the specification code, but isolated from the actual testing logic, which can stay in DBItest for now.

One minor obstacle is that we don't want to introduce import dependencies, but the spec code requires `testthat`. We could make retrieving the actual spec code conditional on the presence of the `testthat` package.

@hadley: Do you have a strong opinion here?

**Comment by hadley** [comment]
Just that the prose explanations need to stay in this package.

**Comment by krlmlr** [comment]
"this package" = DBI?

**Comment by hadley** [comment]
Yes

**Comment by krlmlr** [comment]
Moving the definition of the DBI specs from DBItest to DBI looks too difficult, but DBI will contain a copy of the prose.
