### ISSUE TITLE
Allow invisible logical return values

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#135]
All generics that return a logical should raise an error in case of failure (#51), and return TRUE otherwise (for compatibility). Because the return value is practically useless (at least in interactive mode), it should be invisible, but this is possible only if `valueClass = "logical"` is _not_ defined for these generics.

It looks like lifting this requirement doesn't have an effect on existing backends.

**Comment by krlmlr** [comment]
@hadley: Do you think d1172628 is too much of an evil hack for DBI? I want generics like dbClearResult() to return invisibly, but this doesn't seem possible if the generic has a valueClass.

**Comment by hadley** [comment]
Yeah, it's too much of a hack.

What's the problem with an invisibly return + `valueClass = "logical"` ?

**Comment by krlmlr** [comment]
@hadley: This:

```
> dbDisconnect
standardGeneric for "dbDisconnect" defined from package "DBI"
  defined with value class: "logical"

function (conn, ...) 
{
    ans <- standardGeneric("dbDisconnect")
    .valueClassTest(ans, "logical", "dbDisconnect")
}
<environment: 0x56ef4c8>
Methods may be defined for arguments: conn
Use  showMethods("dbDisconnect")  for currently available ones.
```

The `.valueClassTest()` call always returns a visible value. The only way I see around this is to omit `valueClass`, I guess I'm going to do that.

**Comment by hadley** [comment]
Oh got it. 

I think it's reasonable to omit the `valueClass` since the tests similarly enforce the API.
