### ISSUE TITLE
New sqlInterpolateList() generic

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#140]
Arguments: con, sql, values

The `sqlInterpolate()` function should forward to `sqlInterpolateList()`; only the new function should be implemented by backends and called by other packages, `sqlInterpolate()` is recommended only for interactive use.

CC @yihui @jcheng5 @kevinushey @bborgesr @gaborcsardi.

**Comment by jcheng5** [comment]
Good idea.

**Comment by gaborcsardi** [comment]
@krlmlr I don't know the details to chime in, sorry.

**Comment by krlmlr** [comment]
@gaborcsardi: I think you're using this in revdepcheck. Never mind.

**Comment by gaborcsardi** [comment]
I am using it all the time, just know how it is implemented internally currently, and what your proposed change means.

Btw. why should we only use it interactively? I have in a lot of non-interactive code....

**Comment by krlmlr** [comment]
Interactive: A misnomer, I meant code bound to a specific DB schema.

The change means that callers who start with a list of variables don't have to use `do.call()`.

**Comment by gaborcsardi** [comment]
I see. Yes, that makes sense then.

**Comment by gaborcsardi** [comment]
How about doing it the @hadley way?

```r
sqlInterpolate <- function (`_con`, `_sql`, ..., .values = list()) {
  values <- c(..., .values)
  ...
}
```
Then you can keep it compatible with the current version, and will be more flexible.

The price is that we'll need to write `sqlInterpolate(con, q, .values = vals)`. Personally I would be OK with having to type `.values`, it is more readable anyway.

**Comment by krlmlr** [comment]
I don't quite like the choice of argument names. But I suspect it might be ok to change them to something less tricky, like `.con` or `.sql`.

**Comment by krlmlr** [comment]
Closing in favor of #147.
