### ISSUE TITLE
Change argument names of sqlInterpolate() and sqlParseVariables()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#147]
Use `conn` and `sql` instead of `_con` and `_sql`.

Also add `.dots` argument: https://github.com/rstats-db/DBI/issues/140#issuecomment-251189284.

**Comment by krlmlr** [comment]
@bborgesr @javierlaruschi: I think I have found a way to declare the generic so that it's compatible with both the old and new signatures.

**Comment by bborgesr** [comment]
@krlmlr, That's not yet implemented, right? I still get an error...

**Comment by krlmlr** [comment]
No, please watch this issue. (And I'm not so sure anymore... We'll figure out something.)

**Comment by krlmlr** [comment]
Could you please test your packages with

```r
devtools::install_github("rstats-db/DBI@b-%23147-dots-only")
```

? It's a bit hacky (see [diff](https://github.com/rstats-db/DBI/compare/b-%23147-dots-only)), but should work with both the old and the new interfaces. If it works, this allows us to:

- release DBI 0.6 independently of pool and sparklyr
- upgrade pool and sparklyr at your convenience (ideally, before release of DBI 0.7; the GitHub version should start using the new interface as soon as possible)
- remove the hack with the DBI 0.7 release

See `?sqlInterpolate` and `?sqlParseVariables` for details. Thanks.

**Comment by bborgesr** [comment]
Wow, clever! It works for me. @krlmlr, please let me know when you release DBI to CRAN (with this change) and I'll make sure to update the implementations of `sqlInterpolate` and `sqlParseVariables` to use the new signature as soon as possible.

**Comment by krlmlr** [comment]
Good news! I'm not releasing to CRAN any time soon, but you should be able to update the implementations to the new signature on GitHub (and use `Remotes: rstats-db/DBI` in `DESCRIPTION`) as soon as possible after this issue is closed.

**Comment by krlmlr** [comment]
On the other hand, why force people to use the GitHub version of DBI? The safer approach would be indeed to wait for the CRAN release of DBI.

**Comment by javierluraschi** [comment]
@krlmlr `sparklyr` works correctly with branch `rstats-db/DBI@b-%23147-dots-only`. Is this expected? In that case, I'll close my PR to sparklyr to address this!

**Comment by krlmlr** [comment]
Will release DBI to CRAN soon, if all revdep checks pass, and then change the signature of these functions in the dev version.

**Comment by javierluraschi** [comment]
@krlmlr with the dev version of `DBI` in `sparklyr` I'm hitting this:

```
library(sparklyr)
library(DBI)

spark_install(version = "2.0.1")
sc <- spark_connect(master = "local", version = "2.0.1")
sqlParseVariables(sc, sql = "SELECT 1")
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

To exit cleanly then run:
```
spark_disconnect_all()
```

Is this expected?

**Comment by krlmlr** [comment]
@javierluraschi: No. I guess this means that I revert my evil, evil hack, and we coordinate the release of DBI and sparklyr. What would be a convenient date for you?

BTW, sorry it took me so long. I thought I'd need to install Spark, but you actually did submit a reprex ;-) Neat!

**Comment by krlmlr** [comment]
@bborgesr: Since pool isn't on CRAN yet, would you mind adding a `Remotes: rstats-db/DBI` section (and a versioned dependency on DBI) to `DESCRIPTION` and switch to the new notation?

**Comment by bborgesr** [comment]
@krlmlr: I'm not sure what's the lesser evil: the people who will be annoyed if pool is not compatible with the latest DBI devel, or the people who will be annoyed if pool with not compatible with DBI from CRAN. But I'll certainly switch to the new notation and merge that into master as soon as DBI hits CRAN.

On a different note, this wasn't introduced now, but is there a reason that the `con` and `...` arguments are not documented in the help page for `sqlParseVariables`? (not that it changes anything on my end, just curious):

![screen shot 2017-02-01 at 2 25 05 am](https://cloud.githubusercontent.com/assets/6527540/22493323/771c2d9c-e827-11e6-99e1-dc017b8737a0.png)

**Comment by krlmlr** [comment]
Thanks. I'll double-check the documentation, I wonder why R CMD check hasn't noticed this.

For the time being, you could tag/branch the current state of `pool` and ask users to install from there if they want compatibility with DBI. If `install_github()` is your preferred method of installation, it's one of:

```r
remotes::install_github("rstudio/pool") # devel DBI
remotes::install_github("rstudio/pool@stable") # CRAN DBI from stable tag/branch
```

**Comment by byapparov** [comment]
@krlmlr I would like to pass parameters into a sql chunk and was wondering if you could point me into the right direction.

I have asked this here: https://github.com/r-dbi/bigrquery/issues/391 :

--- 
I am trying to work out if there is a way to pass parameters to the `sql` chunks connected to bigquery:

```{r setup, include=FALSE}
bq_auth(path = "access_token.json")
db <- dbConnect(
  bigquery(), 
  dataset = 'my_data', 
  project = 'my-project', 
  use_legacy_sql = FALSE
)

parameter_value = 10L

```

```{sql, echo=FALSE, connection=db, output.var="x"}
SELECT @parameter_value
```

```{r}
print(x)
# I want to see 10 here.
```
--- 

I am happy to contribute if changes are required on `bigrquery` or `DBI` packages.
