### ISSUE TITLE
logical types fail to convey from db to data.frame with dbReadTable and dbGetQuery

### ISSUE THREAD

**Issue by ajdamico** [rstats-db/DBI#152]
library(DBI)

	sdb <- dbConnect( RSQLite::SQLite() )
	mdb <- dbConnect( MonetDBLite::MonetDBLite() )

	# trues and falses
	x <- data.frame( col1 = c( TRUE , FALSE ) )

	dbWriteTable( mdb , 'x' , x )
	dbWriteTable( sdb , 'x' , x )

	# zeroes and ones
	dbReadTable( mdb , 'x' )
	dbReadTable( sdb , 'x' )

	# monetdblite has the column correctly stored as a BOOLEAN type
	which_table <- dbGetQuery( mdb , "SELECT id FROM tables WHERE name = 'x'" )
	dbGetQuery( mdb , paste0( "SELECT * FROM columns WHERE table_id = " , which_table ) )
	# therefore, i assume the problem is somewhere reading from the db into the data.frame

cc @hannesmuehleisen

**Comment by hannesmuehleisen** [comment]
This is a bug in both SQLite and MonetDBLite, see https://github.com/hannesmuehleisen/MonetDBLite/issues/15 for the latter

**Comment by imanuelcostigan** [comment]
I've implemented some [post-processing](https://github.com/imanuelcostigan/RSQLServer/blob/master/R/dbi-methods.R#L510) to get this working for RSQLServer

**Comment by krlmlr** [comment]
Closing, as this doesn't seem to be a DBI issue.
