### ISSUE TITLE
Standardise on bit64 package?

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#156]
I think it's the best of the options because you can easily convert it to doubles (losing some precision) or characters (if you want to treat as ids).

**Comment by bquinart** [comment]
From a recent thread on R-devel I understand base R will not support 64 bit integers soon. Do we know if there is a specific reason to not try to address this in base R?
I lack any insight regarding appropriateness of bit64 packake. But I would be very happy if the problem is solved within reasonable timing.

**Comment by hadley** [comment]
We can not address it in base R, and R-core doesn't seem interested, so the question is moot. All we can do is promote the best-of-bad solutions.

**Comment by krlmlr** [comment]
With `bit64` it's very easy to end up with wrong values, just strip the `class` attribute. I was considering a dedicated S3 class that stores lossless data in an attribute and provides `as.character()` and perhaps `as.integer64()` methods.

**Comment by hadley** [comment]
@krlmlr yes, it's a little dangerous, but a lot of work has already been done with bit64. I think it's the best of a bad set of solutions. I think coming up with our own solution is out of scope.

**Comment by krlmlr** [comment]
With the current specs, DBI backends can implement 64-bit support with the bit64 package -- all we specify is that as.numeric() gives the (approximated) value and as.character() gives the accurate value. Both is fulfilled by the bit64 implementation.
