### ISSUE TITLE
Check for all readable objects (tables and views) in dbListTables() and dbExistsTable()

### ISSUE THREAD

**Issue by etiennebr** [rstats-db/DBI#157]
What's the best way to check for all readable objects (for a lack of better word)? For instance, before reading or writing, I'd like to check for tables, views AND materialized view. When reading or writing a table, there is not much distinction between a table and a (materialized) view. I'm looking for an equivalent to `dbExistsTable` or `dbListTables`, but broader.

**Comment by krlmlr** [comment]
I plan to extend the specification for `dbListTables()` and `dbExistsTable()` to views (see e.g. https://github.com/rstats-db/DBI/issues/24#issuecomment-171438500), but ultimately this will require cooperation from the backends. Which DBMS are you accessing?

**Comment by etiennebr** [comment]
Yes, sorry I didn't see #24, this would probably be the perfect fix. I'm using RPostgreSQL (see https://github.com/edzer/sfr/pull/213 for the workaround). Maybe a simpler and more portable solution would be to try to `DBI::readTable(conn, c("schema", "table"))` ? But I can't catch all error messages. This is maybe very DBMS specific though, but I still get an error when attempting to read a missing table e.g.:
```r
suppressWarnings(try(DBI::dbGetQuery(conn_to_postgres, "SELECT * FROM missing"), silent = TRUE))
# Error in postgresqlExecStatement(conn, statement, ...) : 
#   RS-DBI driver: (could not Retrieve the result : ERROR:  relation "missing" does not exist
# LINE 1: SELECT * FROM missing
#                       ^
# )
# NULL
```

**Comment by krlmlr** [comment]
I'd like to use a more robust solution for schema support than the one implemented by RPostgreSQL.

Have you seen [pg_tables](https://www.postgresql.org/docs/9.6/static/view-pg-tables.html) and [pg_views](https://www.postgresql.org/docs/current/static/view-pg-views.html)?

Closing in favor of #24.

**Comment by etiennebr** [comment]
Awesome @krlmlr, apparently pg_tables and views have been there since 9.2! but I hadn't heard about it.
