### ISSUE TITLE
Add temporary argument to dbWriteTable

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#160]
This would allow dplyr to use `dbWriteTable()` instead of its own shims

**Comment by krlmlr** [comment]
It's already specified ([documentation link](http://rstats-db.github.io/DBI/reference/dbWriteTable.html#additional-arguments)), but I'm reluctant to extend the S4 interface, because it looks like this requires updating all backends.

**Comment by hadley** [comment]
Are you sure it's not possible, even if you set `signature` in `setGeneric()`?

**Comment by krlmlr** [comment]
After adding an argument `daft = FALSE` to `DBI::dbWriteTable`, I'm getting

```
Error in rematchDefinition(definition, fdef, mnames, fnames, signature) : 
  arguments (daft) after '...' in the generic must appear in the method, in the same place at the end of the argument list
Error : unable to load R code in package ‘RSQLite’
```

when trying to *install* RSQLite. I'd argue it's not worth the effort to force-update all backends. Still, I'd like to see the "Additional arguments" section between the "Arguments" and "Value" sections in the documentation. Any chance `roxygen2` could support this, and if so how?
