### ISSUE TITLE
download of package ‘DBI’ failed

### ISSUE THREAD

**Issue by owy1** [rstats-db/DBI#166]
> install.packages("DBI")

downloaded 0 bytes

Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/DBI_0.5-1.tgz': status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
Warning in install.packages :
  download of package ‘DBI’ failed

**Comment by krlmlr** [comment]
DBI has been upgraded recently on CRAN, could you please try another CRAN mirror?

**Comment by owy1** [comment]
Hello krlmlr,
thanks, the CA mirror works.
ophelia
