### ISSUE TITLE
RStudio still pointing to old, missing package

### ISSUE THREAD

**Issue by mcoirad** [rstats-db/DBI#174]
`> install.packages("DBI")`
`Installing package into ‘C:/Users/Dario.Mitchell/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)`

`trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/DBI_0.6.zip'`

`Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/DBI_0.6.zip': HTTP status was '404 Not Found'`

`Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/DBI_0.6.zip'`

`Warning in install.packages :
  download of package ‘DBI’ failed`

I realize now this should be pointed at 'DBI_0.6-1.zip'

**Comment by krlmlr** [comment]
Could you please reformat your input and the output?
