### ISSUE TITLE
Tweak dbWriteTable and dbReadTable generics

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#18]
Since doing that now will require changes by downstream deps.

```
setGeneric("dbReadTable", valueClass = "data.frame",
  signature = c("conn", "name"),
  function(conn, name, row.names = FALSE, ...) {
    standardGeneric("dbReadTable")
  }
)
setGeneric("dbWriteTable", valueClass = "logical", 
  signature = c("conn", "value"),
  function(conn, name, value, row.names = FALSE,
           overwrite = FALSE, append = FALSE, ...) {
    standardGeneric("dbWriteTable")
  }
)

#' @param row.names An string giving the DBMS column name to use for row
#'   names. Alternatively, a logical flag, where \code{TRUE} means use a 
#'   column called \code{row.names}, and \code{FALSE} means don't store
#'   row names.
#' @param overwrite a logical specifying whether to overwrite an 
#'   existing table or not. Its default is \code{FALSE}
#' @param append a logical specifying whether to append to an existing 
#'   table in the DBMS.  Its default is \code{FALSE}.  
```

**Comment by krlmlr** [comment]
`field.types` and `temporary` seem to be common for dbWriteTable(), too; check.names = TRUE and select.cols = "*" is sometimes used for dbReadTable(). How about a simple "options" object (S3 or even plain list) to avoid future interface clashes?

**Comment by hadley** [comment]
* Deprecate `field.types`,  `check.names` and `select.cols`.

* Options object is not worth the effort because these functions are mostly for backward compatbility

**Comment by krlmlr** [comment]
I think we did agree on not supporting `field.types` if `append == TRUE`. Implementations should throw an error then, just like with `append && overwrite`.

**Comment by krlmlr** [comment]
Arguments are tested and also part of the specs, but not defined in the generic, because this imposes heavy restrictions on how methods must be declared.
