### ISSUE TITLE
Supplying a list for sqlInterpolate?

### ISSUE THREAD

**Issue by cmdcolin** [rstats-db/DBI#193]
Can sqlInterpolate be made to handle a query such as "SELECT * from blah where column IN ?list", where I can supply an R list to sqlInterpolate?

**Comment by krlmlr** [comment]
I don't think this is currently possible, but I vaguely remember a related issue in this repo.

**Comment by cmdcolin** [comment]
That would be really great. I am sort of concerned about an sql injection in my app in this particular use case, because I'm just using sprintf to make the query. Are there are workarounds you would recommend instead of this?

**Comment by krlmlr** [comment]
Maybe something like `SQL(paste(dbQuoteString(...), sep = ", "))` is already safe enough?

**Comment by cmdcolin** [comment]
That seems good, I wrangled it together kind of like this
        quoted = lapply(mylist, function(elt) {
            dbQuoteString(conn, elt)
        })
        generated = paste0('(', do.call(paste, c(quoted, sep = ',')), ')')

**Comment by krlmlr** [comment]
Depending on the backend you use `dbQuoteString()` may be not vectorized (yet).

**Comment by cmdcolin** [comment]
Yep, postgresql in my case. I guess if there are not plans to implement the list operation for sqlInterpolate, then this can be closed for now.  I could imagine it being a little non-trivial

**Comment by scottgigante** [comment]
In case anyone is interested, I have what I think is a slightly safer workaround than the one from @cmdcolin above:
```
sqlInterpolateList <- function(conn, sql, vars=list(), list_vars=list()) {
  if (length(list_vars) > 0) {
    for (name in names(list_vars)) {
      sql <- sub(paste0("\\?", name), paste("?", name, "_list_var", 1:length(list_vars[[name]]), sep="", collapse=" , "), sql)
    }
    list_vars <- lapply(list_vars, function(sublist) {
      names(sublist) <- paste0("list_var", 1:length(sublist))
      sublist
    }) %>% unlist()
    # unlist gives names as "outer.inner" but DBI doesn't like names with periods
    names(list_vars) <- sub("\\.", "_", names(list_vars))
    vars <- c(vars, list_vars)
  }
  statement <- DBI::sqlInterpolate(conn, sql, .dots=vars)
}
```

**Comment by asimve** [comment]
Hi, there is a way which I am using. Just create a dataframe in which put all your list values in a single cell separated by comma(Put quotes around value is you are passing string). Then in sqlinterpolate, refer to that column.
Example: query3<-sqlInterpolate(ANSI(),query2,tst = pop$pop_id)
Here tst is the variable in Sql query in which I'm passing values stored in Pop_id column(note:- All values in a single cell)

**Comment by romunov** [comment]
@asimve I noticed that this solution doesn't work if name is non-numeric as the result doesn't get properly quoted.

E.g.
```
<SQL> SELECT name, id FROM mytable WHERE name IN (FTR, 10)
```

As I understand, this is not a valid SQL statement and thus fails on `dbGetQuery` with error

```
> dbGetQuery(conn = db, statement = xy)
Error in result_create(conn@ptr, statement) : no such column: FTR
```

even though the entries are there. Using solution from @scottgigante works out of the box.
