### ISSUE TITLE
Deprecate dbDriver

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#21]
So we can standardise on one way of connecting to a database: `dbConnect(RSQLite::SQLite())`

**Comment by krlmlr** [comment]
@hadley: I wonder if there's a good way to infer the constructor just from the package name or environment. Maybe provide a registration entry point in DBI?

**Comment by hadley** [comment]
I don't think adding another way to get the database driver is a good solution here. IMO it's better to be explicit.
