### ISSUE TITLE
Better definition of dbGetQuery

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#25]
e.g.

``` R
setMethod("dbGetQuery", signature("MyConnection", "character"),
  function(conn, statement, ..., params = NULL, row.names = NA) {
    rs <- dbSendQuery(conn, statement, params = params, ...)
    on.exit(dbClearResult(rs))

    dbFetch(rs, n = -1, ..., row.names = row.names)
  }
)
```

**Comment by krlmlr** [comment]
This seems to require adding `params` to the interface of `dbSendQuery()`, too. Would make sense imo.

**Comment by hadley** [comment]
I think we should add `params` to the arguments to the `dbGetQuery()` generic because it is so important for modern SQL programming.

**Comment by krlmlr** [comment]
Thinking more about it, I'd prefer a new verb dbSendQueryParam() = dbSendQuery() + dbBind() with a default implementation in DBI. (We could add param to dbGetQuery(), though.) Reason: The current RSQLite implementation (and probably others) don't release the result set if the dbBind() call fails, getting it right (and testing it) is tedious.

**Comment by krlmlr** [comment]
Define dbSendQueryRaw() without parameters, and a default dbSendQuery() that forwards to ...Raw().

**Comment by hadley** [comment]
Then default implement looks something like this:

```R
setMethod("dbSendQuery", c("DBConnection", "character"),
  function(conn, statement, params = NULL, ...) {
    rs <- dbSendQueryRaw(conn, statement)
    on.exit(dbClearResult(rs), add = TRUE)
    
    if (!is.null(params)) {
      dbBind(rs, params)
    }
    on.exit(NULL, add = FALSE)
    
    rs
  }
  ```

**Comment by hadley** [comment]
Here's what a `tryCatch()` implementation would look like:

```R
setMethod("dbSendQuery", c("DBConnection", "character"),
  function(conn, statement, params = NULL, ...) {
    rs <- dbSendQueryRaw(conn, statement)
    
    if (!is.null(params)) {
      tryCatch(
        dbBind(rs, params), 
        error = function(e) {
          dbClearResult(rs)
          stop(e)
        }
      )
    }
    
    rs
  }
)
```

**Comment by krlmlr** [comment]
Wraps the on.exit():

```R
setMethod("dbSendQuery", c("DBConnection", "character"),
  function(conn, statement, params = NULL, ...) {
    rs <- dbSendQueryRaw(conn, statement)

    tryFirstOrRunSecond(
      dbBind(rs, params),
      dbClearResult(rs)
    )
    
    rs
  }
  ```

**Comment by hadley** [comment]
```R
on_error <- function(expr, cleanup) {
  tryCatch(expr, error = function(e) {
    cleanup
    stop(e)
  })
}
```

**Comment by krlmlr** [comment]
The on.exit() version:

```R
on_error <- function(expr, cleanup) {
  on.exit(cleanup)
  expr
  on.exit(NULL)
}
```

**Comment by hadley** [comment]
That would need to be

```R
on_error <- function(expr, cleanup) {
  on.exit(cleanup)
  expr
  on.exit(NULL)
  expr
}
```

I think

**Comment by krlmlr** [comment]
Totally forgot about the return value. Nice trick! Visibility is lost, but to me that's a minor problem -- withVisible() cripples the call stack again.

**Comment by krlmlr** [comment]
withVisible() adds only one entry to the call stack, I confused it with source() which calls withVisible(eval(...)):

```R
on_error <- function(expr, cleanup) {
  on.exit(cleanup)
  ret <- withVisible(expr)
  on.exit(NULL)
  if (ret$visible) ret$value else invisible(ret$value)
}
```

**Comment by krlmlr** [comment]
I'm not too sure we need yet another dbSendQuery() generic. My argument from above (https://github.com/rstats-db/DBI/issues/25#issuecomment-221365147) doesn't hold anymore -- RSQLite implementation is fixed, and we'll be testing that unreleased result sets give a warning on gc() in https://github.com/rstats-db/DBItest/issues/103, so we can also test that a failed dbBind() releases the result set.

**Comment by krlmlr** [comment]
Closing in favor of #76.
