### ISSUE TITLE
Implement default print methods

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#26]

**Comment by krlmlr** [comment]
Instead of `show()`?

**Comment by hadley** [comment]
I think I meant implement default show methods so that packages don't have to copy and paste - if you look at the existing show methods across packages you'll see that they're very similar.

**Comment by hadley** [comment]
DBIDriver, DBIConnection and DBResult already have default `show()` methods, but they only display the class (and connection status). It would be useful if they instead displayed information from the generics that all backends should implement.

I don't think implementing a `format()` is worthwhile here.

**Comment by krlmlr** [comment]
Closing in favor of #163.
