### ISSUE TITLE
Enhance documentation: dbReadTable and dbWriteTable

### ISSUE THREAD

**Issue by stephlocke** [rstats-db/DBI#28]
Currently dbWriteTable doesn't have it's own help file, and the existing documentation is skimpy (at a single line)

It would really beneficial if these functions could have separate entries.

In the dbWriteTable's documentation it would be helpful if it could explain what happens in typical INSERT scenarios like:
- you pass in a field to the primary key that is auto-incrementing
- you don't pass in a primary key value when it's not auto-incrementing
- you pass in more or fewer columns than the table takes
- you pass in a duplicate key value i.e. does it update or error

**Comment by hadley** [comment]
I'd be happy to answer those questions if I knew the answers :stuck_out_tongue:. I think they should all error (except maybe the 3rd), but I don't know for sure, and it might vary by dbms.

**Comment by stephlocke** [comment]
Good point - might be driver dependent, I'm used to working with ODBC so most databases would respond similarly as a consequence under *my* normal usage scenarios.

**Comment by krlmlr** [comment]
Thanks. DBI has no notion of primary keys, so testing this in a generic way across backends looks hard. Column name mismatch will be tested and specified as part of https://github.com/rstats-db/DBItest/issues/93. The documentation for these functions will very soon contain a prose version of the specification of the function's behavior as defined by the tests, so may be a bit too verbose ;-)
