### ISSUE TITLE
feature request: open a client session within R

### ISSUE THREAD

**Issue by ajdamico** [rstats-db/DBI#29]
just an idea..  currently DBI transmits command to and from an external database through commands like `dbGetQuery`.  i'm curious if it's possible (and hopefully easy) to include a new feature that turns an R session into a "client mode" -- sort of like debugger mode, but one specific DBI connection.

so, for example, a user who types
> dbGetQuery( con , "select * from blah" )
> dbGetQuery( con , "select * from blah2" )
> dbGetQuery( con , "select * from blah3" )

could instead type `dbClient` or something like that, and the prompt could change

> dbClient( con )
entering DBI client mode
client[1]> select * from blah;
client[1]> select * from blah2;
client[1]> select * from blah3;
client[1]> Q
exiting DBI client mode
>

and each of those results would print to the screen, the same way they print to the screen from the equivalent `dbGetQuery` calls above.  thank you for DBI!

**Comment by hannesmuehleisen** [comment]
How about something along the following lines:
````R
dbClient <- function(conn, n=100) {
	cat("Enter SQL queries below. CTRL-C to exit.\n")
	on.exit({
		cat("Last result set in variable 'dbcr'.\n")
	})
	repeat {
		tryCatch({
			repeat {
				query <- scan(file="", 
					what=character(), n=1, 
					sep="|", quiet=T, multi.line=F, 
					quote=NULL)

				if (length(query) < 1) {
					next
				}
				ret <- dbGetQuery(conn, query)
				print(head(ret, n))
				dbcr <<- ret
				break
			}}
		, error = function(e) {
			message(e, "\n")
		})
	}
}
````

**Comment by krlmlr** [comment]
This looks nice and useful to me. @hadley: Can we add this to DBI?

**Comment by hadley** [comment]
This feels like a job for another package to me.

**Comment by hannesmuehleisen** [comment]
MonetDB.R will have it in a generic way in the next release, so you can use that :)

**Comment by ajdamico** [comment]
thanks!  from an organizational perspective, i'm curious:  what's the advantage of separating this from `DBI`?  is it comparatively too low-level?

**Comment by hadley** [comment]
It's too high-level - it just doesn't seem like a good fit to the rest of DBI to me.

**Comment by ajdamico** [comment]
cool.  thanks all

**Comment by krlmlr** [comment]
@jbryer: Would such a function be a good fit for your sqlutils package?

**Comment by jbryer** [comment]
Can you provide more details about this feature request? I am not entirely
sure what you are asking for.

**Comment by krlmlr** [comment]
The code shown in https://github.com/rstats-db/DBI/issues/29#issuecomment-103991066 is a simple interactive query processing loop. It shows a prompt, waits for the user to input a SQL query, executes it, and prints the result.

Hannes said, this code is now in the MonetDB.R package. I'm wondering if it could (also) live in your sqlutils package. Perhaps you also want to offer the user an option to save a query entered interactively to a file.
