### ISSUE TITLE
add dbBuildIndex() and dbBuildKey()

### ISSUE THREAD

**Issue by beanumber** [rstats-db/DBI#30]
Could these be added? Something like this should do it:

```
setMethod("dbBuildIndex", signature("DBIConnection", "character"), 
          function(conn, tablename, cols, indexname = NULL, ...) {
            if (is.null(indexname)) {
              indexname <- paste(paste0(cols, collapse = ""), "idx", sep = "_")
            }
            statement = paste("CREATE INDEX", indexname, "ON", tablename, 
                              "(", paste0(cols, collapse=","), ")", sep = " ")
            rs <- dbGetQuery(conn, statement, ...)
          }
)
```

I can send a pull request if you are interested.

**Comment by hadley** [comment]
Seems reasonable to me. I'd be happy to review a pull request. Maybe it should be called `dbCreateIndex()`?

**Comment by hadley** [comment]
I'm not fundamentally opposed to this, but I'm worried about a slippery slope - if we can create indexes, do we also need functions to modify and delete them? If you can create, modify and delete indexes, why can't you do the same for views?   There's also no reason that this couldn't go in a separate package.

**Comment by beanumber** [comment]
@hadley I see your point, but maybe those *should* be features in DBI. 

I guess at some level it is a question about what you want this package to be. Should it just be a way to read from a DB and force all the management of the RDBMS to those developers to do outside of R? If we are going to provide a mechanism for writing data from R to SQL tables (e.g. `dbWriteTable()`), then why not VIEWs? And even though R doesn't have the concept of indices, why shouldn't R users have the capacity to create them? One might even argue that to allow people to create SQL tables without providing a means for them to create indices is encouraging bad practice!

I can see that this opens up a can of worms. But maybe it's a can of worms of manageable size that would taste pretty good here. 

If it did go to a separate package, what would that look like? `DBIadmin`?

**Comment by krlmlr** [comment]
FWIW, dplyr::db_create_index() seems to offer an implementation already. It's another question if that functionality should be part of dplyr or of a different package.
