### ISSUE TITLE
Design question: Should drivers reexport methods they don't override?

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#32]
Example: `dbGetQuery` has a good default implementation. Examples in the driver packages call `library(DBI)` now -- if they don't, the example [fails](https://travis-ci.org/rstats-db/RSQLite/builds/69247259#L1799).

Should DBI advise reexporting everything that is not overridden in the driver?

**Comment by hadley** [comment]
I don't think so - my expectation is that you'll use DBI like this:

```R
library(DBI)
db <- dbConnect(RMySQL::MySQL())
```

i.e. you attach DBI, but not RMySQL.

**Comment by krlmlr** [comment]
This makes sense. Are there any strong reasons against adding `DBI` to `Depends`?

**Comment by krlmlr** [comment]
We probably don't need examples in the backend packages in the first place.
