### ISSUE TITLE
nvarchar column type definition

### ISSUE THREAD

**Issue by yonicd** [rstats-db/DBI#35]
hi i am trying to run a query with hebrew characters e.g.

    con <- dbConnect(RSQLite::SQLite(), dbname="chain_db.sqlite3")
    x=dbGetQuery(con,"select itemname from mega_prices_tbl WHERE itemname LIKE '%אגס%' limit 5")

it returns to x first 5 rows regardless of filter. i get same results when i try it in dplyr form. 

sample of db is [here](https://github.com/yonicd/supermarketprices/raw/master/sql/chain_db.sqlite3)
the dataframe columns are all utf8 when moved to the database.

after looking around i got to 

  - http://stackoverflow.com/questions/27597849/sqlite-using-like-and-hebrew
  - http://stackoverflow.com/questions/15143262/sql-query-in-c-sharp-not-support-hebrew

in the second link they talk about adding N before search term

    select ProductName From Products WHERE TypeOfProduct = N'מעבד'

DBI code:
    
     x2=dbGetQuery(con,"select itemname from mega_prices_tbl WHERE itemname LIKE N'%אגס%' limit 5")
     Error in sqliteSendQuery(con, statement, bind.data) : 
     # with * as wildcard
     x2=dbGetQuery(con,"select itemname from mega_prices_tbl WHERE itemname LIKE N'*אגס*' limit 5")
     Error in sqliteSendQuery(con, statement, bind.data) : 
     error in statement: near "'*אגס*'": syntax error
and that you also need to make sure that your column is of type nvarchar and not varchar, how can i check the column type in DBI? is there a default type? can it be controlled?

    x1 <- dbSendQuery(con,"select * from mega_prices_tbl limit 5")
    dbColumnInfo(x1)
    [1] name   Sclass type   len   
    <0 rows> (or 0-length row.names)

**Comment by krlmlr** [comment]
Thanks. If this is related to SQLite only, please file a new issue in https://github.com/rstats-db/RSQLite, and please also include a reproducible example (e.g., a stripped-down version of your database, or code that creates such a database).

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen/comment.
