### ISSUE TITLE
Timestamp lost from datasets spanning daylight savings

### ISSUE THREAD

**Issue by ebassein** [rstats-db/DBI#36]
When using dbGetQuery for time series data, if the date range includes daylight savings the time stamp gets set to midnight for all entries. 

SO question here: http://stackoverflow.com/questions/31660362/time-lost-from-datetime-element-because-of-daylight-savings-using-dbi-package

sqlQuery() from ROBDC has an option called as.is to import everything as text, which isn't ideal, but is a work around. Is there a similar (or better) solution for DBI?

Thanks!

**Comment by hadley** [comment]
That's a backend specific issue - you need to file a bug with the corresponding package.
