### ISSUE TITLE
Handling of empty strings

### ISSUE THREAD

**Issue by lukebornn** [rstats-db/DBI#37]
R DBI seems to have some strange behavior with empty strings. Here's an example from my problem:

dbGetQuery(con, 'select distinct stringCol, length(stringCol), stringCol="" from db_table;')

  | stringCol |    length(stringCol) | stringCol="" 
 --- | --- | --- | ---
1     |            |      0      |                    1 
2   |  now      |      3            |              0 
3   |  later      |     5           |                0 

Which is fine. However, if I add a sql "where" clause on another variable, things get weird:

dbGetQuery(con, 'select distinct stringCol, length(stringCol), stringCol="" from db_table where col2="something";')

  | stringCol |    length(stringCol) | stringCol="" 
 --- | --- | --- | ---
1  |   now        |       3                |            0
2   |  now         |      0                 |           1
3   |  later        |       5                 |          0

**Comment by hadley** [comment]
DBI is a generic interface. You need to file a bug with the respective backend (and including a reproducible example would be much appreciated)
