### ISSUE TITLE
An argument to suppress messages. 

### ISSUE THREAD

**Issue by statwonk** [rstats-db/DBI#38]
I've noticed that `dbSendQuery` has the side-effect of returning db messages like,

`INFO:  Load into table 'test' completed, 10 record(s) loaded successfully.` from postgres.

The message isn't suppressible via `suppressMessages` nor `suppressWarnings`.

My use-case is a cronjob that uses a DBI connection to load data. The message above is sent from R to stderr. If there's an actual error `dbSendQuery` will throw and R error, so I'd like to separate the two.

There are ways to suppress these types of messages at the db-level, but I'd argue that the message above should be returned to R as a message (that could either be suppressed or redirected).

I'm not sure how to solve the problem above, but I'd be happy to do research or submit a PR if someone has some guidance.

**Comment by hadley** [comment]
That's a backend issue. Please file a minimal reprex at the RPostgres repo.
