### ISSUE TITLE
Rcpp dependency

### ISSUE THREAD

**Issue by jangorecki** [rstats-db/DBI#40]
Current CRAN stable DBI is not dependent (or imports) on the Rcpp package, while the current latest version master branch here on github does Imports Rcpp. This is quite heavy dependency which I'm currently not using in multiple production environments. I would prefer not to be forced to include that dep. Any chance to move Rcpp to Suggests or make a non-Rcpp branch? If the Rcpp is now a fundamental dep for DBI maybe it would be better to name it DBI2 so the non-Rcpp DBI can simultaneously exists.

**Comment by hadley** [comment]
I think correct escaping is very important. I don't think minimising deps that most people will have any way (since rcpp is most downloaded package) is important.
