### ISSUE TITLE
Don't encourage depending on DBI in backend vignette

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#41]
> This is one of the few situations in which using depends (instead of imports) is correct, because you want to make sure the generics from the DBI package (like dbConnect(), dbGetQuery() etc) are available.

This is from the backend vignette -- should be changed to "import DBI".

Closes rstats-db/RPostgres#47.

Related: rstats-db/RSQLite#102.

**Comment by krlmlr** [comment]
Fixed in 9f77c37362886abc7a95 (part of #44).

**Comment by krlmlr** [comment]
@hadley: Not having DBI in "Depends" breaks existing examples that assume DBI on the search path. What's your preferred way to handle this situation?

**Comment by hadley** [comment]
Tell users that the need to attach DBI but not the specific backend.

**Comment by krlmlr** [comment]
How to tell `R CMD check`?

**Comment by hadley** [comment]
Explicitly use `library(DBI)` in the examples

**Comment by krlmlr** [comment]
Closed in #44.

**Comment by hannesmuehleisen** [comment]
Just a quick confirmation, so I should have Imports: DBI in my DESCRIPTION file?

**Comment by hadley** [comment]
@hannesmuehleisen yes

**Comment by hannesmuehleisen** [comment]
@hadley this dropped me into this situation (http://r-pkgs.had.co.nz/namespace.html): "A method for a generic in a suggested package. Namespace directives must refer to available functions, so they can not reference suggested packages. It’s possible to use package hooks and code to add this at run-time, but this is sufficiently complicated that I currently wouldn’t recommend it. Instead, you’ll have to design your package dependencies in a way that avoids this scenario.". Any hint on how to do this even if its not recommended?

**Comment by krlmlr** [comment]
See e.g. https://github.com/krlmlr/RPostgres/tree/feature/dbi-test for a working example of `Imports: DBI`. This is different from `Suggests: DBI`, to which the passage you quote seems to apply.

**Comment by hannesmuehleisen** [comment]
@krlmlr don't think thats related? I have a `Enhances: dplyr` in my `DESCRIPTION` file and the s3 methods that I export worked because the package used to be attached. Since this is supposed to change I ran into the mentioned issue where functions are no longer found, e.g. 

```
> MonetDB.R::src_monetdb(embedded=tempdir())
Error in UseMethod("src_desc") : 
  no applicable method for 'src_desc' applied to an object of class "c('src_monetdb', 'src_sql', 'src')"
```

**Comment by krlmlr** [comment]
What happens with the code below?

```
s <- MonetDB.R::src_monetdb(embedded=tempdir())
s
```

**Comment by hannesmuehleisen** [comment]
same thing of course

**Comment by krlmlr** [comment]
I asked because `src_desc()` is called from `format.src()` (<- `print.src()`), both in `dplyr`. Does the error show after the first or the second statement?

**Comment by hannesmuehleisen** [comment]
second.

**Comment by krlmlr** [comment]
Have you implemented and exported `src_desc.src_monetdb()` in MonetDB.R?

**Comment by hannesmuehleisen** [comment]
Yes of course and this used to work fine if the package is attached. It does not work however if it is merely loaded.

**Comment by krlmlr** [comment]
Strange. Could you point me to the branch of your code where I can see the behavior?

**Comment by krlmlr** [comment]
Looking at the CRAN version, I think I see what you mean, but I'm still not sure how your question is related to DBI and the Depends -> Imports change.

**Comment by hannesmuehleisen** [comment]
never mind figured it out
