### ISSUE TITLE
A syntax for managing db schemas?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstats-db/DBI#43]
I had issues with managing schemas with `MonetDB` and `MonetDB.R` - see [question in SO and my own answer here] (http://stackoverflow.com/questions/33027517/how-to-manage-schemas-in-r-monetdb), but in the process I realised that it is `DBI` that lacks a clear syntax to guide developers.

I wonder if it is in the pipeline?

Incidentally this is not a new issue.  It has been raised [before](https://github.com/rstats-db/DBI/issues/24).

**Comment by krlmlr** [comment]
Let's continue discussion in #24.
