### ISSUE TITLE
JSON type in PostGreSQL

### ISSUE THREAD

**Issue by chasset** [rstats-db/DBI#47]
Hello,

It looks like the `jsonb` variable type is not implemented in the PostGreSQL driver of DBI. Is it?
Best regards,

Pierre-Olivier

**Comment by krlmlr** [comment]
I don't think there is such a type, but there might be some limited support. Could you please file an issue in https://github.com/rstats-db/RPostgres that describes what you're trying to achieve and where the package doesn't behave the way you expect?
