### ISSUE TITLE
Lists of raw vectors should map to blobs by default

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#49]
RPostgres, RMySQL and RSQLite map those to BLOBs. However, DBI doesn't declare the `dbDataType` method for lists, and the BLOB data type doesn't seem to be part of SQL-92.

Shall we add

```
setMethod("dbiDataType", "list", function(x) "blob")
```

to DBI?

CC @hannesmuehleisen.

**Comment by hannesmuehleisen** [comment]
fine with me.

**Comment by hadley** [comment]
How would lists get serialised into the database? I think this is part of a broader issue of allowing people to register custom serialisers and deserialisers for non-standard SQL types/R classes.

**Comment by krlmlr** [comment]
Lists (with `raw` vectors inside) already seem to be serialized as BLOBs in the existing rstats-db backends, but I don't have a test for that yet.

**Comment by hadley** [comment]
On option would be to do something like this:

```R
setMethod("dbiDataType", "list", function(x) {
  is_raw <- vapply(x, is.raw, logical(1))
  if (all(is_raw)) {
    return("blob")
  }
  
  stop("Only lists of raw vectors are currently support", call. = FALSE)
})
```

**Comment by krlmlr** [comment]
A thin S3 wrapper is another option:

```
as.raw_list <- function(x) {
  check_raw_list(x)
  structure(x, class = "raw_list")
}
```

Here, the checking needs to be done only once during construction.
