### ISSUE TITLE
Remove max.connections from requirements for dbGetInfo(Driver)

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#56]
Instead of dbGetInfo(Driver) entry.

**Comment by hadley** [comment]
Actually I think this should go away altogether - it's an artefact of the older style of implementing backends.

**Comment by krlmlr** [comment]
this = max.connections, or dbGetInfo()?

**Comment by hadley** [comment]
Clarified - I'll delete this comment and yours

**Comment by hannesmuehleisen** [comment]
@hadley +1.

**Comment by hannesmuehleisen** [comment]
I am not sure in general what the purpose of the `getInfo` functions is and who actually uses those.

**Comment by krlmlr** [comment]
At the very least, this allows a general-purpose implementation of show().

**Comment by hannesmuehleisen** [comment]
Yes but which properties are used there?

**Comment by krlmlr** [comment]
The help for dbGetInfo() has a "wish list". We can start from that, and DBItest would test those, too. See also #54

**Comment by hadley** [comment]
I think it would be better to provide an extremely basic show method in DBI, and then assume backend authors will provide richer methods.
