### ISSUE TITLE
Unclutter documentation index

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#59]
Example:

**dbHasCompleted**	Has the operation completed?
**dbHasCompleted-method**	Has the operation completed?

One of these should go away.

**Comment by hadley** [comment]
I'm not sure that's possible :/

**Comment by krlmlr** [comment]
What happens (apart from the desired effect) if we ditch the alias that seems to generate this?

https://github.com/rstats-db/DBI/blob/7a0ad76dea21a846cee62f67108ab8e8b7d60a49/R/DBResult.R#L161

**Comment by hadley** [comment]
You get an error that the S4 method isn't documented.

We could possibly alias all the methods to a dummy help doc with `@keyword internal`, but that would break `methods?dbHasCompleted`.

**Comment by hadley** [comment]
FWIW with latest roxygen, I think you can use `@rdname` instead of manually creating the aliases.

**Comment by krlmlr** [comment]
Thanks, I forgot about R CMD check. FWIW, `methods?dbHasCompleted"` seems to be broken.

**Comment by hadley** [comment]
Sorry, I always forget how you look up methods - it should be ` ?dbConnect(RSQLite::SQLite())` or similar.

**Comment by krlmlr** [comment]
It's strange that I don't get R CMD check errors on R 3.2.2 -- `dbConnect()` doesn't have the required alias, no duplicate entry in the index, still `?dbConnect(RSQLite::SQLite())` works (and `?dbConnect("a")` doesn't).
