### ISSUE TITLE
A Query class as an alternative to param argument?

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#63]
Might require fewer API changes in the end. Would probably be S4, but S3 equivalent looks like this:

```
Query <- function(sql, params = NULL) {
  structure(list(sql=sql, params=params), class = "Query")
}

c.Query <- function(...) {
  queries <- list(...)
  zipped <- purrr::zip_n(queries)
  structure(
    list(sql = paste(zipped$sql, collapse = "\n"),
         params = unlist(zipped$params, recursive = FALSE)),
    class = "Query")
}
```

The `c()` makes it much easier to combine queries with parameters. ~~Only works with positional placeholders, though -- need to add support for ?-style placeholders to Postgres (via `sqlInterpolate()`).~~

**Comment by hannesmuehleisen** [comment]
*cough* purr dependency?

**Comment by krlmlr** [comment]
Just to save a few lines of code in the example :-)

**Comment by hannesmuehleisen** [comment]
ah ok :)

**Comment by krlmlr** [comment]
Could be built into the existing `SQL` class.

The `dbSendQuery()` and `dbGetQuery()` functions could gain a default implementation with `signature("DBIconnection", "SQL")` that makes use of the `sqlInterpolate()` function and forwards to `signature("DBIconnection", "character")`. `dbBind()` will be unnecessary. I think this will simplify coding both for backend implementers and interface users.

**Comment by krlmlr** [comment]
Parametrized queries:

- Safety
- Performance

Coding examples follow.

**Comment by krlmlr** [comment]
Seems that we need dbBind() after all.

# Code examples

## Construction

```
sql <- SQL("SELECT a + :offset FROM tbl WHERE b < :threshold", list(offset = 1, threshold = 10))
```

## Concatenation and updating

```
sql_select <- SQL("SELECT a + :offset")
sql_from <- SQL("FROM tbl WHERE b < :threshold", list(threshold = 10))
sql_partial <- c(sql_select, sql_from)
sql <- SQL(sql_partial, list(offset = 1))
```

## Preparation

- Sends the query to the server
- If all parameters are given, executes it
- Otherwise waits for dbBind()

```
res <- dbSendQuery(con, sql)
```

## Updating arguments

- Closes result set if it was open (with warning)
- Reuses prepared query
- Keeping more than one *closed* result set should be supported -- to make sure that prepared queries stay prepared

```
res <- dbBind(res, list(offset = 2, threshold = 100))
```

**Comment by krlmlr** [comment]
Out of scope.
