### ISSUE TITLE
Better tools for restarting dropped connections

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBI#64]
I think this means:
- Testing that `dbIsValid()` returns FALSE is a connection is broken
- Testing that `dbConnect(con)` clones and re-opens a broken connection

**Comment by hannesmuehleisen** [comment]
MonetDB.R already supports something like that.

**Comment by igoldin2u** [comment]
`dbIsValid()` seems broken right now, at least with MySQL.

    > dbcon <- dplyr::src_mysql(...)
    # Database server drops connection
    > db_tables <- DBI::dbListTables(dbcon$con)
    Error in .local(conn, statement, ...) : could not run statement: MySQL server has gone away
    > DBI::dbIsValid(dbcon$con)
    [1] TRUE
    > dbcon <- src_mysql(....)
    > DBI::dbIsValid(dbcon$con)
    [1] TRUE

**Comment by hadley** [comment]
Is this mostly superseded by pool now?

**Comment by krlmlr** [comment]
@bborgesr: I don't know enough about pool's internals, could you please comment?

**Comment by bborgesr** [comment]
Yeah, if you're using `pool`, this functionality is covered... I guess the question is if you want to support this directly in `DBI`, as a first class feature of connections... But if you're just happy that there is a way of doing this by using another package, then this is not that relevant anymore. If you need me to go into more detail about how `pool` does this, let me know, but it's basically performing an existence query on the existing connection and if that doesn't work, we just fetch a new connection.

**Comment by hadley** [comment]
Given that pool supports this, I think it's no longer necessary to be part of DBI itself.
