### ISSUE TITLE
Meaningless return value for dbClearResult()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#65]
Currently returns TRUE for the existing backends, regardless of state. One of the following should happen:
- Return invisible NULL
- Return value based on the state of the result set
- Error if already closed

**Comment by hannesmuehleisen** [comment]
like the invisible NULL here. Don't think it should throw an error ever.

**Comment by krlmlr** [comment]
Closing in favor of #135, which will probably return TRUE invisibly.
