### ISSUE TITLE
request: add INSERT REPLACE and INSERT IGNORE functionality

### ISSUE THREAD

**Issue by beanumber** [rstats-db/DBI#68]
This would have to be added to the constituent packages. 

So, instead of `dbWriteTable()` having arguments to `overwrite` or `append`, what if the `append` argument to take any of `c(TRUE, FALSE, replace, ignore)`? [I'm most familiar with MySQL so I am thinking in that syntax, but any decent RDBMS must have similar functionality, right?]

I suppose a more natural alternative would be to have a function called `dbInsert()` and then just have `dbWriteTable()` invoke that where appropriate.

**Comment by hannesmuehleisen** [comment]
>  any decent RDBMS must have similar functionality, right?

No.

**Comment by krlmlr** [comment]
More detail: https://en.wikipedia.org/wiki/Merge_(SQL). This seems to be widely supported, though, and (of course) mostly with different syntax. Backends that don't support this feature could simply throw an error.

What is the benefit of having a dbInsert() function?

**Comment by beanumber** [comment]
The benefit would be to be able to update and existing table with new data, without having to either overwrite *the whole table* or append *only new rows*. 

There are (at least) three things that you might want to do to an existing table with a primary key defined:
1. Truncate the existing table and insert the new data
2. Keep the old data and add the new rows that don't conflict with the old data while throwing away the new rows that do. (e.g. `INSERT IGNORE`)
3. Keep the old data and add the new rows, but also update the old data with the new data when there is a key conflict. (e.g. `INSERT REPLACE`)

`overwrite=TRUE` does 1. But `append=TRUE` doesn't do 2 or 3, right? It just throws an error?

**Comment by krlmlr** [comment]
Let's discuss this in #74.
