### ISSUE TITLE
Default implementation for dbDataType()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#70]
- Doesn't work with arguments of unknown class ("AsIs", "unknown1"), as required by DBItest
    - I don't remember why I added this requirement, but it may be better to err on the safe side here
- Need implementation for lists (#49)
- Need implementation for hms/difftime (#42)
- Should return objects of class `SQL` (https://github.com/rstats-db/RPostgres/pull/45#issuecomment-200960432)
- For data frames, a named list should be returned

**Comment by imanuelcostigan** [comment]
Default implementation fails DBItest for AsIs `Date` and `DateTime`. Not sure whether this is an issue for 

```R
dbDataType(ANSI(), I(Sys.Date()))
#> [1] "DOUBLE"
```

Maybe something like this in `as_is_data_type()`?

```R
dd <- I(Sys.Date())
class(dd) <- class(dd)[-1]
```
