### ISSUE TITLE
Improve default implementation of dbQuoteString() and dbQuoteIdentifier()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#77]
- [x] Single quotes for **S**trings: http://stackoverflow.com/a/1992331/946850, escape by repetition~~, escape backslash, escape single quote with backslash~~
- [x] Double quotes for **D**atabase stuff, escape by repetition
- [x] Vectorize dbQuoteString()
- [x] Add dots in dbQuoteIdentifier()
- [x] Return "SQL" object

**Comment by hadley** [comment]
I'm not sure we should provide too much by default - most database APIs provide explicit quoting/escaping functions which should be used preferentially to doing this in R.

**Comment by imanuelcostigan** [comment]
@krlmlr dbQuoteIdentifier should **not** return a vector which the current implementation does (fails DBItest `quote_identifier_not_vectorized`)

**Comment by krlmlr** [comment]
@imanuelcostigan: Yes, that's the plan. I'll look into making the documentation clearer. (Could you please fix the reference link?)

**Comment by krlmlr** [comment]
I'm now convinced that dbQuoteIdentifier() should be vectorized, because this seems to be the standard with most existing backends. We'll figure out another way to provide schema information.

**Comment by hadley** [comment]
I think something that creates a schema object is probably the way forward: `dbQuoteIdentifer(con, schema("x", "y"))`

**Comment by krlmlr** [comment]
@hadley: This looks complicated. I'd like to keep the vectorized nature and avoid using new classes if at all possible.

Please see https://github.com/rstats-db/DBI/issues/24#issuecomment-275946619 for the current design. Happy to take your feedback there.
