### ISSUE TITLE
Think about columns in dbColumnInfo() output

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#78]
`dbColumnInfo()` returns a data frame, currently with "name" and "type" columns (as tested by DBItest and implemented by backends) but the documentation specifies "name", "field.type" and "data.type" columns.

This method seems to be new, so we're free to choose what to do here.

**Comment by hadley** [comment]
It would be nice to have one column that gives the SQL type and one column that gives the R type.

**Comment by krlmlr** [comment]
Needs to be tested in DBItest.
