### ISSUE TITLE
DBI depending on Rcpp?

### ISSUE THREAD

**Issue by hannesmuehleisen** [rstats-db/DBI#82]
I would like to suggest DBI not depending on Rcpp. The rationale here is that an interface package should be as independent as possible, and Rcpp is a huge dependency. Also, when considering alternative R implementations, having DBI depend on it is not desirable since these alternative implementations are unlikely to support Rcpp.

On closer review, I see that Rcpp is only used to parse SQL strings. IMHO, this is also not really a job for DBI to semantically analyze the query strings.

**Comment by krlmlr** [comment]
The string analyzer is there for providing parametrized queries even if the backend doesn't support it (https://github.com/rstats-db/DBI/issues/63#issuecomment-171457926) . Most backends require a native library, would they be supported in these alternative implementations?

Rcpp is huge, on the other hand I think it's now safe to assume that it's available virtually everywhere.

**Comment by hannesmuehleisen** [comment]
Aand C++ is required to do this somehow? It's not like this is performance critical or so.

**Comment by krlmlr** [comment]
Parsing strings in R is painful, wouldn't you agree?

**Comment by hannesmuehleisen** [comment]
It might not be fun but no reason to pull in Rcpp for a fallback implementation.

**Comment by hadley** [comment]
The C++ is not so much for performance, but because it's easier to verify correctness. I'd be happy to review a PR, but we're planning on a release in the very near future, so it would need to be ready soon.

**Comment by hannesmuehleisen** [comment]
Created a pull request and slightly expanded test cases.
