### ISSUE TITLE
gc() corruption-related crashes introduced in 3.2.4 affecting DBI occurs on memory overload

### ISSUE THREAD

**Issue by ajdamico** [rstats-db/DBI#88]
hi, r core has disclaimed responsibility for this bug.  this bug is hugely disruptive for DBI users and it's likely a gc() bug not a DBI bug but i do not have the technical know-how to distill this down any further than i already have.  the examples provided to the r-core team are minimal and easily reproducible, but (as they correctly mention) rely on this contributed package.

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16734

could someone on the DBI team please help me reconfigure my minimal reproducible example so that we can re-open this r-project ticket?  here's how simple it is

	# initiate R with "C:\Program Files\R\R-3.2.4\bin\x64\Rterm.exe" --max-mem-size=35M
	library(RSQLite)
	db <- dbConnect( SQLite() )
	for( i in 1:1000 ) { dbWriteTable( db , 'x' , mtcars , append = TRUE ) }
	# CRASH

thank you!

cc @hannesmuehleisen

**Comment by krlmlr** [comment]
35 MB is not a lot memory for R. What happens if you allow for more memory?

**Comment by ajdamico** [comment]
hi kirill, it does not crash as quickly, but the R console should never crash.  the tiny amount of memory is a helpful way to pinpoint this bug.

**Comment by krlmlr** [comment]
Could you please show the crash output?

**Comment by ajdamico** [comment]
there is none.  here's what happens.. thanks!



	C:\Windows\System32> "C:\Program Files\R\R-3.2.3\bin\x64\Rterm.exe" --max-mem-size=35M

-------
	
	R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
	Copyright (C) 2015 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> library(RSQLite)
	Loading required package: DBI
	> db <- dbConnect( SQLite() )
	> for( i in 1:1000 ) { dbWriteTable( db , 'x' , mtcars , append = TRUE ) }

-------
	
	C:\Windows\System32>

**Comment by ajdamico** [comment]
edited my original issue because the bug has carried over to 3.2.4 cc @hannesmuehleisen

**Comment by hadley** [comment]
This is unlikely to be a DBI issue, but instead is much more likely to be an RSQLite issue. Can you please file there?

**Comment by hadley** [comment]
(FWIW I can't replicate on my computer, but there's no `--max-mem-size` parameter on the mac. It may well be fixed in the dev version)
