### ISSUE TITLE
Deprecate columnToRownames() and rownamesToColumn()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#91]
in favor of tibble.

Also un-export Table class for now.

**Comment by krlmlr** [comment]
rownamesToColumn() is used by sqlData(), can't simply remove it. Options:

- [ ] Move sqlXXX() and Table class back to SQL package
    - My favorite: Now easier to handle with "Remotes" support in devtools
- [ ] Change sqlData() to not call rownamesToColumn(), remains responsibility of the caller
- [ ] Keep rownamesToColumn() here, but don't export
- [ ] Support rownamesToColumn() and columnToRownames()
    - Essentially the same as in tibble, only default name changes
- [ ] Import tibble
    - @hannesmuehleisen won't like that
- [ ] Add source file from tibble to this package

@hadley: Your preference?

**Comment by hadley** [comment]
Hmmm, I'd be in favour of not-deprecating them since I think they need different defaults to tibble. We could give them more specific names if you want.

**Comment by krlmlr** [comment]
I guess it's ok to have different functions for different use cases.

Function names: I'd go with the "sql" prefix used for the other functions.

**Comment by hadley** [comment]
Yeah, I agree that the `sql` prefix would be best
