### ISSUE TITLE
could not find function "columnToRownames"

### ISSUE THREAD

**Issue by mabodo** [rstats-db/DBI#95]
Aa for today I strated to find an error when using RPostgres such as:

`Error in .local(res, n, ...) : could not find function "columnToRownames"`

By error I added the original DBI and RPostgres libraries. 

My code is really simple.

```
install.packages("devtools")
devtools::install_github("RcppCore/Rcpp"E)
devtools::install_github("rstats-db/DBI")
devtools::install_github("rstats-db/RPostgres")


library(DBI)
library(RPostgres)

con <- dbConnect(RPostgres::Postgres(),
                 <connection properties>)

test <- dbListTables(con)
```

Any idea were I might be mistaking?

Thanks in advance,

DAVID

**Comment by krlmlr** [comment]
Sorry, forgot to push. Could you reinstall RPostgres and try again?

**Comment by mabodo** [comment]
I reinstalled BH i thought it solved the problem. But I just realize maybe it was you... :)

Thanks in any case!
