### ISSUE TITLE
Breaking change on recent DBI columnToRownames rename

### ISSUE THREAD

**Issue by robertzk** [rstats-db/DBI#96]
@krlmlr Can you update the package version in light of https://github.com/rstats-db/DBI/commit/dec68f09fbb2a084b562b65574866026ba037e23 ? It broke some of my recent builds after the [accompanying update to RPostgres](https://github.com/rstats-db/RPostgres/commit/f219d0b2cf4465a3ea832a6d8470f43e12bb3c0f) and I have no way to determine if my end user is using an older version of DBI without something clunky like `if (exists("columnToRownames", envir = getNamespace("DBI")))`

For reference, an example failing build: https://travis-ci.org/robertzk/cachemeifyoucan/builds/121746790

**Comment by robertzk** [comment]
Nevermind - you changed an internal interface and I forgot I had forked the package at my own peril.

**Comment by krlmlr** [comment]
The interface is public, but hasn't been published to CRAN yet. It's ok to depend on it, once DBI is released which will happen very soon.
