### ISSUE TITLE
Function to sanitize SQL

### ISSUE THREAD

**Issue by gaborcsardi** [rstats-db/DBI#99]
Although the new data binding will we awesome, it would be nice to be able to directly sanitize a string to prevent injections.

**Comment by krlmlr** [comment]
Does sqlInterpolate() work for you?

**Comment by gaborcsardi** [comment]
Oh, I guess it does, thanks! Sorry, I didn't find it, used the wrong keywords.

**Comment by krlmlr** [comment]
Then it might be worthwhile to improve the documentation. What keywords did you use?

There's also dbQuote() and dbQuoteString().

**Comment by gaborcsardi** [comment]
AFAIR I search for `sanitize` and `escape`.

**Comment by gaborcsardi** [comment]
Btw. are there plans for the next release. I could release use the data binding, and also `sqlInterpolate`.

**Comment by krlmlr** [comment]
Release is overdue, but waiting helped fix a minor issue and release burden on downstream maintainers. I'm planning to release in the next couple of days.

**Comment by gaborcsardi** [comment]
\o/

**Comment by gaborcsardi** [comment]
Thanks much for the release!
